export const INSERT_QUESTION = 'INSERT_QUESTION';
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const UPDATE_QUESTION = 'UPDATE_QUESTION';


export const INSERT_ANSWER = 'INSERT_ANSWER';
export const REMOVE_ANSWER = "REMOVE_ANSWER";
export const UPDATE_ANSWER = 'UPDATE_ANSWER';


export const INSERT_QUIZ = 'INSERT_QUIZ';
export const REMOVE_QUIZ = "REMOVE_QUIZ";
export const UPDATE_QUIZ = 'UPDATE_QUIZ';

export const INSERT_MESSAGE = 'INSERT_MESSAGE';
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const INSERT_FILE = 'INSERT_FILE';
export const REMOVE_FILE = "REMOVE_FILE";
export const UPDATE_FILE = 'UPDATE_FILE';

export const INSERT_SESSION = 'INSERT_SESSION';
export const REMOVE_SESSION = "REMOVE_SESSION";
export const UPDATE_SESSION = 'UPDATE_SESSION';

export const INSERT_COURSE = 'INSERT_COURSE';
export const REMOVE_COURSE = "REMOVE_COURSE";
export const UPDATE_COURSE = 'UPDATE_COURSE';


export const NAVIGATE_TO = 'NAVIGATE_TO';
export const GO_BACK = 'GO_BACK';
export const RESET_ROUTE = 'RESET_ROUTE';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
