export const INSERT_QUESTION = 'INSERT_QUESTION';
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const UPDATE_QUESTION = 'UPDATE_QUESTION';


export const INSERT_ANSWER = 'INSERT_ANSWER';
export const REMOVE_ANSWER = "REMOVE_ANSWER";
export const UPDATE_ANSWER = 'UPDATE_ANSWER';


export const INSERT_QUIZ = 'INSERT_QUIZ';
export const REMOVE_QUIZ = "REMOVE_QUIZ";
export const UPDATE_QUIZ = 'UPDATE_QUIZ';

export const INSERT_COURSE = 'INSERT_COURSE';
export const REMOVE_COURSE = "REMOVE_COURSE";
export const UPDATE_COURSE = 'UPDATE_COURSE';


export const NAVIGATE_TO = 'NAVIGATE_TO';
export const GO_BACK = 'GO_BACK';
export const RESET_ROUTE = 'RESET_ROUTE';
