export const INSERT_QUESTION = 'INSERT_QUESTION';
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const UPDATE_QUESTION = 'UPDATE_QUESTION';


export const INSERT_ANSWER = 'INSERT_ANSWER';
export const REMOVE_ANSWER = "REMOVE_ANSWER";
export const UPDATE_ANSWER = 'UPDATE_ANSWER';

export const NAVIGATE_TO = 'NAVIGATE_TO';
export const GO_BACK = 'GO_BACK';
export const RESET_ROUTE = 'RESET_ROUTE';
